--TIPOS DE EMPLEADOS
INSERT INTO EMPLOYEE_TYPES (TYPE_EMPLOYEE)
VALUES ('FACER');

--EMPLEADOS
INSERT INTO EMPLOYEES (NAME, LASTNAME,ID_TYPE_EMPLOYEE, NICKNAME, PASSWORD)
VALUES ('JULIAN', 'MARK', 1 , 'JMARK', '123');
INSERT INTO EMPLOYEES (NAME, LASTNAME,ID_TYPE_EMPLOYEE, NICKNAME, PASSWORD)
VALUES ('DANIELA', 'SANZ', 1 , 'DSANZ', '123');

--ORGANIZACIONES SOCIALES Y CIVILES
INSERT INTO OSC (DESCRIPTION)
VALUES ('AFULIC');
INSERT INTO OSC (DESCRIPTION)
VALUES ('SOLES');

--lOCALIZACION DE LAS CAMPANIAS
INSERT INTO LOCATIONS (DESCRIPTION)
VALUES ('CORDOBA');

--TIPOS DE CAMPANIAS
INSERT INTO CAMPAIGN_TYPES (DESCRIPTION)
VALUES ('ITINERANCIA');
INSERT INTO CAMPAIGN_TYPES (DESCRIPTION)
VALUES ('VIA PUBLICA');
INSERT INTO CAMPAIGN_TYPES (DESCRIPTION)
VALUES ('EVENTOS');

--CAMPANIAS
INSERT INTO CAMPAIGNS (NAME, ID_LOC, ID_OSC, ID_TYPE_CAMPAIGN)
VALUES ('RIO CUARTO',1,1,1);
INSERT INTO CAMPAIGNS (NAME, ID_LOC, ID_OSC, ID_TYPE_CAMPAIGN)
VALUES ('VILLA ALLENDE',1,2,1);

--EQUIPOS
--EMPLEADO JULIAN ID 1 CAMPAÑA 1 OSC AFULIC ID 1
INSERT INTO TEAM_EMPLOYEES (ID_EMPLOYEE, INITIAL_DATE, FINAL_DATE,ID_CAMPAIGN)
VALUES (1, SYSDATE, NULL, 1);
--EMPLEADO DANIELA ID 2 CAMPAÑA 1 OSC AFULIC ID 1
INSERT INTO TEAM_EMPLOYEES (ID_EMPLOYEE, INITIAL_DATE, FINAL_DATE,ID_CAMPAIGN)
VALUES (2, SYSDATE, NULL, 1);

--TIPO DE PAGOS
INSERT INTO PAY_TYPES (DESCRIPTION)
VALUES ('CREDITO');
INSERT INTO PAY_TYPES (DESCRIPTION)
VALUES ('DEBITO');

--DONACIONES EMPLEADO JULIAN ID 1 CAMPAÑA 1 OSC AFULIC ID 1
INSERT INTO DONATIONS (NAME, LASTNAME, DNI, DATE_BIRTH ,GENDER,
	MOBILE, PHONE, ADDRESS, CITY, PROVINCE,
	AMOUNT, CARD_NUMBER, CARDHOLDER, DNI_CARDHOLDER, EXPIRATION_DATE,
	OBSERVATION, ID_TYPE_PAY, ID_EMPLOYEE_TEAM, ID_CAMPAIGN, CREATE_DATE)
VALUES ('JUANA','PEREZ','31646181', TO_DATE('1957/10/02', 'yyyy/mm/dd'),'F',
	'3518113800','3518113811','RIO NEGRO 2105','CORDOBA','CORDOBA',
	300, '471777881212','JUANA PEREZ','31646181', TO_DATE('2022/05', 'yyyy/mm'),
	'HOLA VOS', 1, 1, 1, SYSDATE);

INSERT INTO DONATIONS (NAME, LASTNAME, DNI, DATE_BIRTH ,GENDER,
	MOBILE, PHONE, ADDRESS, CITY, PROVINCE,
	AMOUNT, CARD_NUMBER, CARDHOLDER, DNI_CARDHOLDER, EXPIRATION_DATE,
	OBSERVATION, ID_TYPE_PAY, ID_EMPLOYEE_TEAM, ID_CAMPAIGN, CREATE_DATE)
VALUES ('PAULA','JORDAN','35675543',TO_DATE('1975/05/03', 'yyyy/mm/dd'),'F',
	'3518113812','3518113815','VELEZ 123','CORDOBA','CORDOBA',
	500, '47166445454','PAULA JORDAN','35675543',TO_DATE('2020/10', 'yyyy/mm'),
	'', 2, 1, 1, SYSDATE);
INSERT INTO DONATIONS (NAME, LASTNAME, DNI, DATE_BIRTH ,GENDER,
	MOBILE, PHONE, ADDRESS, CITY, PROVINCE,
	AMOUNT, CARD_NUMBER, CARDHOLDER, DNI_CARDHOLDER, EXPIRATION_DATE,
	OBSERVATION, ID_TYPE_PAY, ID_EMPLOYEE_TEAM, ID_CAMPAIGN, CREATE_DATE)
VALUES ('MARIO', 'SUAREZ', '31646183', TO_DATE('1987/04/12', 'yyyy/mm/dd'),'M',
	'3518113455','3518113443','PIRCAS 48', 'SAN FRANCISCO', 'CORDOBA',
	400, '588543432121', 'MARIO SAUREZ', '31646183', TO_DATE('2023/12', 'yyyy/mm'),
	'NO LLAMAR', 1, 1, 1, SYSDATE);
--FIN DONACIONES EMPLEADO JULIAN ID 1 CAMPAÑA 1 OSC AFULIC ID 1

--DONACIONES EMPLEADO DANIELA ID 2 CAMPAÑA 1 OSC AFULIC ID 1
INSERT INTO DONATIONS (NAME, LASTNAME, DNI, DATE_BIRTH ,GENDER,
	MOBILE, PHONE, ADDRESS, CITY, PROVINCE,
	AMOUNT, CARD_NUMBER, CARDHOLDER, DNI_CARDHOLDER, EXPIRATION_DATE,
	OBSERVATION, ID_TYPE_PAY, ID_EMPLOYEE_TEAM, ID_CAMPAIGN, CREATE_DATE)
VALUES ('SAMANTA','ROMERO', '23646181', TO_DATE('1967/10/03', 'yyyy/mm/dd'),'F',
	'3564323243','','LOS BOULEVARES 12', 'SAN MARCOS', 'CORDOBA',
	350, '453245452323', 'SAMANTA ROMERO', '23646181', TO_DATE('2021/05', 'yyyy/mm'),
	'', 1, 2, 1, SYSDATE);
--FIN DONACIONES EMPLEADO DANIELA ID 2 CAMPAÑA 1 OSC AFULIC ID 1


--REGISTRO DIARIO EMPLEADO JULIAN ID 1 CAMPAÑA 1 OSC AFULIC ID 1
INSERT INTO DAILY_RECORDS (ID_EMPLOYEE_TEAM, ID_CAMPAIGN, PRODUCTIVE_HOURS, NON_PRODUCTIVE_HOURS, CREATE_DATE)
VALUES ((SELECT ID_EMPLOYEE FROM TEAM_EMPLOYEES WHERE ID = 1), 1, 3, 1, TO_DATE('2020/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'));
--FIN REGISTRO DIARIO EMPLEADO JULIAN ID 1 CAMPAÑA 1 OSC AFULIC ID 1

--REGISTRO DIARIO EMPLEADO DANIELA ID 2 CAMPAÑA 1 OSC AFULIC ID 1
INSERT INTO DAILY_RECORDS (ID_EMPLOYEE_TEAM, ID_CAMPAIGN, PRODUCTIVE_HOURS, NON_PRODUCTIVE_HOURS, CREATE_DATE)
VALUES ((SELECT ID_EMPLOYEE FROM TEAM_EMPLOYEES WHERE ID = 2), 1, 5, 3, TO_DATE('2020/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'));
--FIN REGISTRO DIARIO EMPLEADO DANIELA ID 2 CAMPAÑA 1 OSC AFULIC ID 1

--DESVICULACION DE EMPLEADO JULIAN ID 1 DEL EQUIPO DE LA CAMPANIA 1
UPDATE TEAM_EMPLOYEES SET FINAL_DATE = SYSDATE WHERE ID_EMPLOYEE = 1;

--VINCULACION DE EMPLEADO JULIAN ID 1 AL EQUIPO DE LA CAMPANIA 2
INSERT INTO TEAM_EMPLOYEES (ID_EMPLOYEE, INITIAL_DATE, FINAL_DATE,ID_CAMPAIGN)
VALUES (1, SYSDATE, NULL, 2);



INSERT INTO DAILY_RECORDS (ID_EMPLOYEE_TEAM, ID_CAMPAIGN, PRODUCTIVE_HOURS, NON_PRODUCTIVE_HOURS, CREATE_DATE)
VALUES (1, 2, 3, 1, TO_DATE('2020/12/23 21:02:44', 'yyyy/mm/dd hh24:mi:ss'));
INSERT INTO DAILY_RECORDS (ID_EMPLOYEE_TEAM, ID_CAMPAIGN, PRODUCTIVE_HOURS, NON_PRODUCTIVE_HOURS, CREATE_DATE)
VALUES (1, 2, 5, 1, TO_DATE('2020/12/24 21:02:44', 'yyyy/mm/dd hh24:mi:ss'));
